# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
                ('raca', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[(b'cachorro', 'Cachorro'), (b'gato', 'Gato'), (b'passaro', 'P\xe1ssaro')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.DateTimeField()),
                ('nome', models.CharField(choices=[(b'banho', 'Banho'), (b'cirurgia', 'Cirurgia'), (b'consulta', 'Consulta')], max_length=50)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Animal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('tipos', models.CharField(choices=[(b'cliente', 'Cliente'), (b'medico', 'M\xe9dico'), (b'funcionario', 'Funcion\xe1rio')], max_length=50)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Animal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='procedimento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Usuario'),
        ),
    ]
